[package]
edition = "2021"
name = "codegen"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbindgen = "0.20.0"
liquid = "0.26.0"
serde = "1.0.136"

[build-dependencies]
lib-ruby-parser-nodes = {version = "0.49.0"}
