[package]
authors = ["Ilya Bylich <ibylich@gmail.com>"]
edition = "2018"
name = "ruby-parser-c"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[features]
default = []

onig = ["lib-ruby-parser/onig"]

own-structures = ["lib-ruby-parser/compile-with-external-structures"]

[dependencies]

[dependencies.lib-ruby-parser]
features = ["compile-with-external-structures"]
version = "3.0.7"

[profile.dev]
panic = "abort"

[profile.release]
debug-assertions = false
incremental = false
lto = true
overflow-checks = false
panic = "abort"
