name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-lib:
    name: build lib file (target = ${{ matrix.build.target }})
    runs-on: ${{ matrix.build.os }}
    env:
      BUILD_ENV: release
      TARGET: ${{ matrix.build.target }}
      CC: ${{ matrix.build.cc }}
      LD: ${{ matrix.build.ld }}
      AR: ${{ matrix.build.ar }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cc: clang-12
            ld: ld.lld-12
            ar: llvm-ar-12
            lib_file: libruby_parser_c.a
            output_artifact_name: libruby_parser_c-x86_64-unknown-linux-gnu.a

          - os: macos-latest
            target: x86_64-apple-darwin
            cc: clang
            ld: ld
            ar: ar
            lib_file: libruby_parser_c.a
            output_artifact_name: libruby_parser_c-x86_64-apple-darwin.a

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            cc: cl.exe
            ld: link.exe
            lib_file: libruby_parser_c.lib
            output_artifact_name: libruby_parser_c-x86_64-pc-windows-msvc.lib

          - os: windows-latest
            target: x86_64-pc-windows-gnu
            cc: gcc
            ld: ld
            ar: ar
            lib_file: libruby_parser_c.a
            output_artifact_name: libruby_parser_c-x86_64-pc-windows-gnu.a
    steps:
      - name: setup msvc on windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.build.target }}
          override: true

      - name: print rustc detailed version
        run: rustc --version --verbose

      - name: checkout
        uses: actions/checkout@v2

      - name: codegen
        env:
          RUSTFLAGS: ""
        run: cd codegen && cargo build

      - name: make lib file
        run: make ${{ matrix.build.lib_file }}

      - name: upload ${{ matrix.build.output_file }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.build.lib_file }}
          path: ${{ matrix.build.output_artifact_name }}

      - name: benchmark
        run: make benchmark/download && make benchmark/record

      - name: upload ${{ matrix.build.target }}.benchmark-out
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.build.target }}.benchmark-out
          path: ${{ matrix.build.target }}.benchmark-out

  build-header:
    name: build header file
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: checkout
        uses: actions/checkout@v2

      - name: build lib-ruby-parser.h
        run: make lib-ruby-parser.h

      - name: upload lib-ruby-parser.h
        uses: actions/upload-artifact@v2
        with:
          name: lib-ruby-parser.h
          path: lib-ruby-parser.h

  build-release-notes:
    name: build release notes
    needs:
      - 'build-lib'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # download benchmark results
      - uses: actions/download-artifact@v2
        with: { name: x86_64-unknown-linux-gnu.benchmark-out }

      - uses: actions/download-artifact@v2
        with: { name: x86_64-apple-darwin.benchmark-out }

      - uses: actions/download-artifact@v2
        with: { name: x86_64-pc-windows-msvc.benchmark-out }

      - uses: actions/download-artifact@v2
        with: { name: x86_64-pc-windows-gnu.benchmark-out }

      - name: build release notes
        run: |
          ls -l
          echo "### Results for x86_64-unknown-linux-gnu:" >> release_notes.md
          echo "" >> release_notes.md
          cat x86_64-unknown-linux-gnu.benchmark-out >> release_notes.md
          echo "" >> release_notes.md
          echo "### Results for x86_64-apple-darwin:" >> release_notes.md
          echo "" >> release_notes.md
          cat x86_64-apple-darwin.benchmark-out >> release_notes.md
          echo "" >> release_notes.md
          echo "### Results for x86_64-pc-windows-msvc:" >> release_notes.md
          echo "" >> release_notes.md
          cat x86_64-pc-windows-msvc.benchmark-out >> release_notes.md
          echo "" >> release_notes.md
          echo "### Results for x86_64-pc-windows-gnu:" >> release_notes.md
          echo "" >> release_notes.md
          cat x86_64-pc-windows-gnu.benchmark-out >> release_notes.md
          cat release_notes.md

      - name: upload release_notes.md
        uses: actions/upload-artifact@v2
        with:
          name: release_notes.md
          path: release_notes.md

  make-release:
    name: release
    needs:
      - 'build-lib'
      - 'build-header'
      - 'build-release-notes'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # lib files
      - uses: actions/download-artifact@v2
        with: { name: libruby_parser_c-x86_64-unknown-linux-gnu.a }

      - uses: actions/download-artifact@v2
        with: { name: libruby_parser_c-x86_64-apple-darwin.a }

      - uses: actions/download-artifact@v2
        with: { name: libruby_parser_c-x86_64-pc-windows-msvc.lib }

      - uses: actions/download-artifact@v2
        with: { name: libruby_parser_c-x86_64-pc-windows-gnu.a }

      # header file
      - uses: actions/download-artifact@v2
        with: { name: lib-ruby-parser.h }

      # release notes
      - uses: actions/download-artifact@v2
        with: { name: release_notes.md }

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "libruby_parser_c-*,lib-ruby-parser.h"
          bodyFile: release_notes.md
          token: ${{ secrets.GITHUB_TOKEN }}
