name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.build.name }}
    runs-on: ${{ matrix.build.os }}
    env:
      TARGET: ${{ matrix.build.target }}
      CC: ${{ matrix.build.cc }}
      LD: ${{ matrix.build.ld }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: test on linux (clang)
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cc: clang-12
            ld: ld.lld-12
            run: make test

          - name: test on mac (clang)
            os: macos-latest
            target: x86_64-apple-darwin
            cc: clang
            ld: ld
            run: make test

          - name: test on windows (msvc)
            os: windows-latest
            target: x86_64-pc-windows-msvc
            cc: cl.exe
            ld: link.exe
            run: make test

          - name: test on windows (mingw)
            os: windows-latest
            target: x86_64-pc-windows-gnu
            cc: gcc
            ld: ld
            run: gcc --version && make test

          - name: valgrind
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cc: clang-12
            ld: ld.lld-12
            run: make test-valgrind

          - name: asan
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cc: clang-12
            ld: ld.lld-12
            run: ASAN_OPTIONS=detect_leaks=1 CFLAGS="-fsanitize=address" make test

    steps:
      - name: setup msvc on windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      # - name: fix linker on windows
      #   if: runner.os == 'Windows'
      #   run: |
      #     rm "C:\\Program Files\\Git\\usr\\bin\\link.exe"
      #     which -a link.exe

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.build.target }}
          override: true

      - name: checkout
        uses: actions/checkout@v2

      - name: install valgrind
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind libtool-bin

      - name: run tests
        run: ${{ matrix.build.run }}
