name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: ${{ matrix.build.name }}
    runs-on: ${{ matrix.build.os }}
    env:
      CARGO_BUILD_TARGET: ${{ matrix.build.target }}
      CC: ${{ matrix.build.cc }}
      CXX: ${{ matrix.build.cxx }}
      LD: ${{ matrix.build.ld }}
      CARGOFLAGS: ${{ matrix.build.cargoflags }}
      ASAN_OPTIONS: detect_leaks=0
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: test on linux (clang)
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cc: clang-9
            cxx: clang++-9
            ld: ld.lld-9
            cargoflags: --features="onig"
            run: make clean test

          - name: test on mac (clang)
            os: macos-latest
            target: x86_64-apple-darwin
            cc: clang
            cxx: clang++
            ld: ld
            cargoflags: --features="onig"
            run: make clean test

          - name: test on windows (msvc)
            os: windows-latest
            target: x86_64-pc-windows-msvc
            cc: cl.exe
            cxx: cl.exe
            ld: link.exe
            cargoflags: ""
            run: make clean test

          - name: test on windows (mingw)
            os: windows-latest
            target: x86_64-pc-windows-gnu
            cc: gcc
            cxx: g++
            ld: ld
            cargoflags: ""
            run: gcc --version && make clean test

          - name: valgrind
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cc: clang-9
            cxx: clang++-9
            ld: ld.lld-9
            cargoflags: ""
            run: make clean test-valgrind

          - name: asan
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cc: clang-9
            cxx: clang++-9
            ld: ld.lld-9
            cargoflags: ""
            run: ASAN_OPTIONS=detect_leaks=1 CCFLAGS="-fsanitize=address" make clean test

    steps:
      - name: setup msvc on windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: fix linker on windows
        if: runner.os == 'Windows'
        run: |
          rm "C:\\Program Files\\Git\\usr\\bin\\link.exe"
          which -a link.exe

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.build.target }}
          override: true

      - name: checkout
        uses: actions/checkout@v2

      - name: install valgrind
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind libtool-bin

      - name: run tests
        shell: bash
        run: ${{ matrix.build.run }}
