name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.build.name }}
    runs-on: ${{ matrix.build.os }}
    env:
      BUILD_ENV: debug
      RUST_TARGET: ${{ matrix.build.target }}
      CC: ${{ matrix.build.cc }}
      AR: ${{ matrix.build.ar }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: test on linux (clang)
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cc: clang-12
            ar: llvm-ar-12
            run: |
              cmake ..
              make test

          - name: test on mac (clang)
            os: macos-latest
            target: x86_64-apple-darwin
            cc: clang
            ar: ar
            run: |
              cmake ..
              $CC --version
              make test

          - name: test on windows (msvc)
            os: windows-latest
            target: x86_64-pc-windows-msvc
            cc: cl.exe
            run: |
              cmake -G"MinGW Makefiles" ..
              make test

          - name: test on windows (mingw)
            os: windows-latest
            target: x86_64-pc-windows-gnu
            cc: gcc
            ar: ar
            run: |
              cmake -G"MinGW Makefiles" ..
              make test

          - name: valgrind
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cc: clang-12
            ar: llvm-ar-12
            run: |
              sudo apt-get update
              sudo apt-get install -y valgrind libtool-bin
              cmake ..
              make test-runner
              valgrind ./tests/test-runner

          - name: asan
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cc: clang-12
            ar: llvm-ar-12
            run: |
              cmake ..
              ASAN_OPTIONS=detect_leaks=1 CFLAGS="-fsanitize=address" make test

    steps:
      - name: setup msvc on windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.build.target }}
          override: true

      - name: print system info
        run: |
          rustc --version --verbose
          which make
          make --version
          which bash
          bash --version

      - name: checkout
        uses: actions/checkout@v2

      - name: test
        env:
          VERBOSE: "1"
        run: |
          mkdir build
          cd build
          ${{ matrix.build.run }}

  test-header:
    name: test building lib-ruby-parser.h
    runs-on: ubuntu-latest
    env:
      RUST_TARGET: x86_64-unknown-linux-gnu
    steps:
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: checkout
        uses: actions/checkout@v2

      - name: build lib-ruby-parser.h
        env:
          VERBOSE: "1"
        run: |
          mkdir build
          cd build
          cmake ..
          make codegen_main_header

      - name: validate lib-ruby-parser.h
        run: |
          cd build
          clang -fsyntax-only -Wall -Wextra -Wpedantic lib-ruby-parser.h
